### PR TITLE
finaladminupdates-authentication added

### PR DESCRIPTION
**Pull request by supremequeen189**
Authentication added to all users + admins!

### CODE REVIEW

**Comment by michaelrios2015** [comment]
Awesome!! Will check it out tomorrow :)

**Comment by supremequeen189** [comment]
Customer order history/info:
CoffeePeeps

Customer order info:
CoffeePeeps

If you're logged in as an admin (admin1@email.com, pw 123), you can now see the Admin dropdown menu and perform admin functions (which we already reviewed before)
Screen Shot 2021-02-15 at 10 20 58 PM

**Comment by supremequeen189** [comment]
@jsur89 @jakescript @michaelrios2015 FYI!

**Comment by michaelrios2015** [comment]
Code looks great!!

**Comment by jakescript** [comment]
super fancy im loving it :)

**Pull request merged**
